
# Missing packages
#   Adobe source code pro
#   alacritty
#   chromium
#   discord
#   exa
#   starship → on pacman etc.



# Maybe:
#   ansible
#   standard bluetooth
#   ffmpeg
#   gimp
#   gscan2pdf
#   jetbrains toolbox + products
#   jupyter
#   nmap
#   qbittorrent
#   shellcheck
#   spotify
#   steam
#   telegram-desktop
#   texlive
#   thunderbird
#   vlc


# Idk
#   Timeshift

# Uni specific
#   mumble
#   zotero

# Arch specific
#   find-the-command
#   yay


# Garuda dependencies



- include_vars: "{{ item }}"
  with_first_found:
    - "package_translation/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yaml"
    - "package_translation/{{ ansible_distribution }}.yaml"
    - "package_translation/{{ ansible_os_family }}.yaml"
  when: apache_package_name is not defined or apache_service_name is not defined


- name: Install really core packages
  ansible.builtin.package:
    name:
      - curl
      - wget
  become: true



- name: Add deadsnakes repository
  become: true
  apt_repository: repo="ppa:deadsnakes/ppa"
  apt_repository: repo="ppa:fish-shell/beta-3"
  when: ansible_os_family == 'Debian'


- name: Update cache apt
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600 upgrade=dist force_apt_get=yes
  when: ansible_os_family == 'Debian'
  become: true




- name: Install starship
  shell: wget -P /tmp https://starship.rs/install.sh; sh -c "$(cat /tmp/install.sh)" -- -y; mv /usr/local/bin/starship /usr/bin/starship
  become: true
  args:
    creates: /usr/bin/starship


- name: Core packages
  ansible.builtin.package:
    name:
      - bat
      - gcc
      - cmake
      - "{{ exa_package_name | default('') }}"
      - make
      - cowsay
      - direnv
      - fish
      - git
      - htop
      - neofetch
      - neovim
      - "{{ openssh_package_name }}"
      - "{{ pip_package_name }}"
      - "{{ python_package_name }}"
      - rsync
      - vim
      - jq

    state: latest
  become: true

- name: Set login shell to fish
  ansible.builtin.command: usermod --shell /bin/fish {{ ansible_env.USER }}
  become: true
  changed_when: false

- name: Pip packages
  pip:
    name:
      - thefuck
      - tldr
      - ipython
      - sympy
      - numpy






- name: Make bin dir
  file:
    dest: "~/bin/bash_functions_for_fish"
    state: directory



- name: Install dotfiles
  file: 
    path: "{{ item.dest }}"
    state: directory

  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes

  with_items:
    - { src: '~/configAndDotfiles/roles/shell/tasks/dotfiles/alacritty/alacritty.yml', dest: '~/.config/alacritty/alacritty.yml' }
    - { src: '~/configAndDotfiles/roles/shell/tasks/dotfiles/bin/git', dest: '~/bin/git' }
    - { src: '~/configAndDotfiles/roles/shell/tasks/dotfiles/bin/gitbslr.so', dest: '~/bin/gitbslr.so' }
    - { src: '~/configAndDotfiles/roles/shell/tasks/dotfiles/bin/bash_functions_for_fish/update', dest: '~/bin/bash_functions_for_fish/update' }
    - { src: '~/configAndDotfiles/roles/shell/tasks/dotfiles/fish/config.fish', dest: '~/.config/fish/config.fish' }
    - { src: '~/configAndDotfiles/roles/shell/tasks/dotfiles/git/.gitconfig', dest: '~/.gitconfig' }
    - { src: '~/configAndDotfiles/roles/shell/tasks/dotfiles/neofetch/config.conf', dest: '~/.config/neofetch/config.conf' }
    - { src: '~/configAndDotfiles/roles/shell/tasks/dotfiles/neofetch/current_image.txt', dest: '~/.config/neofetch/current_image.txt' }
    - { src: '~/configAndDotfiles/roles/shell/tasks/dotfiles/ssh/config', dest: '~/.ssh/config' }
    - { src: '~/configAndDotfiles/roles/shell/tasks/dotfiles/starship/starship.toml', dest: '~/.config/starship.toml' }
    - { src: '~/configAndDotfiles/roles/shell/tasks/dotfiles/vim/.vim', dest: '~/.vim' }
    - { src: '~/configAndDotfiles/roles/shell/tasks/dotfiles/vim/.vimrc', dest: '~/.vimrc' }



- name: Bootstrapping vim
  command: ~/configAndDotfiles/roles/shell/tasks/dotfiles/vim/.vim/pack/vendor/start/bootstrap.sh
  args:
    chdir: ~/configAndDotfiles/roles/shell/tasks/dotfiles/vim/.vim/pack/vendor/start/
    creates: ~/configAndDotfiles/roles/shell/tasks/dotfiles/vim/.vim/pack/vendor/start/YouCompleteMe
