---

# TODO: backup role
# Add pacman.conf / makepkg.conf
- hosts: localhost

  roles:
    #    - shell
    #    - gui_programming
    #    - gui_basic
    - sway

  environment:
    PATH: /home/emily/.cargo/bin:{{ ansible_env.PATH }}


