---

# TODO: backup role
# Add pacman.conf / makepkg.conf
- hosts: localhost

  roles:
    - shell
      #    - gui_programming
      #    - gui_basic
      #    - i3

  environment:
    PATH: /home/emily/.cargo/bin:{{ ansible_env.PATH }}


