- name: Clone config Repo
  git:
    repo: https://github.com/Emily3403/configAndDotfiles
    dest: ~/configAndDotfiles
    force: yes


- name: Install Kopia
  become: true
  package:
    name:
        - kopia-bin

- name: Install Kopia Systemd Service
  become: true
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644

  with_items:
    - { src: "~/configAndDotfiles/roles/backup/tasks/dotfiles/systemd/kopia.service", dest: "/etc/systemd/system/kopia.service" }

- name: Enable Kopia Service
  systemd_service:
    name: kopia
    state: started
    enabled: true
    daemon_reload: yes
