- name: Clone config Repo
  git:
    repo: https://github.com/Emily3403/configAndDotfiles
    dest: ~/configAndDotfiles
    force: yes

- name: Make dotfile dirs
  file:
    dest: "{{ item }}"
    state: directory

  with_items:
    - '~/.config/i3'
    - '~/.config/polybar'

- name: Install i3 dotfiles
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes

  with_items:
    - { src: "~/configAndDotfiles/roles/i3/tasks/dotfiles/i3/config", dest: "~/.config/i3/config" }
    - { src: "~/configAndDotfiles/roles/i3/tasks/dotfiles/i3/config.d", dest: "~/.config/i3/config.d" }
    - { src: "~/configAndDotfiles/roles/i3/tasks/dotfiles/i3/layouts", dest: "~/.config/i3/layouts" }
    - { src: "~/configAndDotfiles/roles/i3/tasks/dotfiles/polybar/config.ini", dest: "~/.config/polybar/config.ini" }
    - { src: "~/configAndDotfiles/roles/i3/tasks/dotfiles/polybar/macchiato.ini", dest: "~/.config/polybar/macchiato.ini" }
    - { src: "~/configAndDotfiles/roles/i3/tasks/dotfiles/polybar/launch.sh", dest: "~/.config/polybar/launch.sh" }
    - { src: "~/configAndDotfiles/roles/i3/tasks/dotfiles/polybar/scripts", dest: "~/.config/polybar/scripts" }
