# QWERTZ Layout, wir fangen links an.
$mainMod = SUPER
bind = $mainMod, backspace, workspace, 14  # for keepass

# ––– Browsers –––
# Default, 'normal'
workspace = 3, on-created-empty: firefox

# ––– Audio Top Left –––
bind = $mainMod, Escape, workspace, 60
workspace = 60, on-created-empty: obs

bind = $mainMod, F1, workspace, 61
workspace = 61, on-created-empty: pavucontrol

bind = $mainMod, F2, workspace, 62
workspace = 62, on-created-empty: easyeffects

bind = $mainMod, F3, workspace, 63
workspace = 63, on-created-empty: QT_QPA_PLATFORM=wayland mscore

bind = $mainMod, F4, workspace, 64
workspace = 64, on-created-empty: audacity


# ––– 4 Terminals 4 development –––
bind = $mainMod, F5, workspace, 65
workspace = 65, on-created-empty: alacritty

bind = $mainMod, F6, workspace, 66
workspace = 66, on-created-empty: alacritty

bind = $mainMod, F7, workspace, 67
workspace = 67, on-created-empty: alacritty

bind = $mainMod, F8, workspace, 68
workspace = 68, on-created-empty: alacritty


# ––– GUI Applications right –––
bind = $mainMod, F9, workspace, 70
workspace = 70, on-created-empty: Telegram

bind = $mainMod, F10, workspace, 71
workspace = 71, on-created-empty: gtk-launch spotify

bind = $mainMod, F11, workspace, 72
workspace = 72, on-created-empty: thunderbird

bind = $mainMod, F12, workspace, 73
workspace = 73, on-created-empty: superproductivity


# === This is the basis defintion for everything: keepass → 14 ===
workspace = 14, on-created-empty: keepassxc



# ––– Work [INET] 411364 –––


# Incognito Browser
bind = $mainMod, Home, workspace, 50
workspace = 50, on-created-empty: firefox --ProfileManager


bind = $mainMod, End, workspace, 51
bind = $mainMod, Insert, workspace, 52




# --- Workspace Rules ---




