# QWERTZ Layout, wir fangen links an.
$mainMod = SUPER

bind = $mainMod, dead_acute, workspace, 13 # pavucontrol


bind = $mainMod, backspace, workspace, 14  # keepassxc
bind = $mainMod, Escape, workspace, 15     # easyeffects

bind = $mainMod, F1, workspace, 40     # easyeffects




bind = $mainMod, Home, workspace, 50     # easyeffects
bind = $mainMod, End, workspace, 51     # easyeffects
bind = $mainMod, Insert, workspace, 52     # easyeffectsA




# --- Workspace Rules ---
workspace = 12, on-created-empty: thunderbird
workspace = 13, on-created-empty: superproductivity
workspace = 10, on-created-empty: Telegram
workspace = 11, on-created-empty: gtk-launch spotify
workspace = 13, on-created-empty: pavucontrol
workspace = 14, on-created-empty: keepassxc

workspace = 40, on-created-empty: easyeffects



# Work [INET]
workspace = 50, on-created-empty:firefox
