#!/bin/bash
i3-msg append_layout $HOME/i3bin/i3layouts/layout_discord.json
i3-msg "[title=DiscordUnique] move scratchpad"
i3-msg append_layout $HOME/i3bin/i3layouts/layout_discord.json

/usr/bin/discord
