[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold", "-C", "target-cpu=native"]

[target.aarch64-unknown-linux-gnu]
linker = "zig-cc"
rustflags = ["-C", "link-arg=--target=aarch64-linux-gnu"]
